### ISSUE TITLE
Consider adding gpuproxy to SeaORM showcase!

### ISSUE THREAD

**Issue by billy1624** [ipfs-force-community/gpuproxy#13]
Hey @hunjixin, feel free to submit a PR to showcase your project!
- https://github.com/SeaQL/sea-orm/issues/403

**Comment by hunjixin** [comment]
@billy1624 i will add it

**Comment by billy1624** [comment]
Thanks! @hunjixin

**Comment by Fatman13** [comment]
老 issue 先关掉了。
